### ISSUE TITLE
create an ics feed

### ISSUE THREAD

**Issue by aoloe** [libregraphicsmeeting/htdocs-2016#17]
examples:

- <https://bitbucket.org/ms-studio/head-construction/src/d6862c215ed9525176ca474162f1d7d6f158b38f/page-ical.php?at=master&fileviewer=file-view-default> used in <http://head.hesge.ch/construction/agenda/>
- https://github.com/aoloe/htdocs-bc_oberurdorf/blob/master/htdocs/module/ICS_Feed.php

**Comment by aoloe** [comment]
a first version is online:

http://libregraphicsmeeting.org/2016/schedule.ics

it validates...

i just have to figure out what to put in the description...

**Comment by barbarogenius** [comment]
can i publish this?

**Comment by aoloe** [comment]
if it's good enough for you, go for it!

**Comment by barbarogenius** [comment]
just checked it - looks good but the starting times are +1 hour from the planned times

**Comment by aoloe** [comment]
should be correct now: it now set (planned time -1) in the file (UTC) which should translate to the correct GMT+1 in the reader.
can you check if it works correctly?

**Comment by barbarogenius** [comment]
hiya,

unfortunately it did not change start time + when i was checking it on ical - it was showing links to individual talk pages that dont exist

**Comment by aoloe** [comment]
for the time, i don't know what to do...
i consider that showing the UTC time (so the actual time -1) is the correct thing to do, but ical seems not do the +1 needed for the summer time.
i have only have little experience with those files and until now it always worked correctly (probably because the server was/is in the same timezone as the event).

if somebody knows how to fix this line

https://github.com/libregraphicsmeeting/htdocs-2016/blob/master/themes/lgm2016/page-schedule-ics.php#L88
(or any other faulty line)

help is welcome!

concerning the links: i will have to check this evening.

**Comment by aoloe** [comment]
for the time, i don't know what to do...
i consider that showing the UTC time (so the actual time -1) is the correct thing to do, but ical seems not do the +1 needed for the summer time.
i have only have little experience with those files and until now it always worked correctly (probably because the server was/is in the same timezone as the event).

if somebody knows how to fix this line

https://github.com/libregraphicsmeeting/htdocs-2016/blob/master/themes/lgm2016/page-schedule-ics.php#L88
(or any other faulty line)

help is welcome!

concerning the links: i will have to check this evening.

**Comment by aoloe** [comment]
i have to check:
- http://stackoverflow.com/questions/23963459/importing-ics-into-google-calendar-with-correct-timezone

**Comment by signalwerk** [comment]
this is super nice and works perfect for me! it would probably help if you could publish a link online, so people can find it. thanks a lot!

**Comment by barbarogenius** [comment]
yes, thanks for reminder - times are all ok now, will publish! thank you aoloe!

**Comment by aoloe** [comment]
nice!
let's hope that we will have less issues next year :-)
