### ISSUE TITLE
webbanner

### ISSUE THREAD

**Issue by barbarogenius** [libregraphicsmeeting/htdocs-2016#19]
Hello,

Someone on the interwebz told me the LGM logo has jaggy diagonal lines
and provided a replacement:

http://i.imgur.com/XkOhqw4.png

Alex
_______

**Comment by aoloe** [comment]
... it's empty here...

**Comment by barbarogenius** [comment]
how do you mean its empty? :) 

here's the link again: http://i.imgur.com/XkOhqw4.png

**Comment by aoloe** [comment]
empty?

see the ascii screenshot below...

**Comment by barbarogenius** [comment]
there's no ascii screenshot - it must be i dont understand. would it work if i rename the image alex sent and put it in the design/banner folder?

**Comment by aoloe** [comment]
on this firefox it shows correctly. on chrome it did show... nothing.

and, yes, please add it to the designer folder!

ciao
al.e

**Comment by barbarogenius** [comment]
i'm getting error every time i try to upload the file:
Something went really wrong, and we can’t process that file. 

will try again wee bit later.

**Comment by barbarogenius** [comment]
ok, so this is done and looks better on the test server http://lgm2016.4o4.ch/

how do we push this to the main site?

**Comment by aoloe** [comment]
@ms-studio can you please upload the file? (it's not group writable...)

**Comment by ms-studio** [comment]
Done!
