### ISSUE TITLE
Add people to the repository

### ISSUE THREAD

**Issue by ms-studio** [libregraphicsmeeting/htdocs-2016#2]
This ticket is for adding contributors who will be working on the LGM 2016 website.

For a start, our super admin ( @aoloe ) needs to add the following users:

@jperezgraphics (student)
@phiLangley
@barbarogenius (Larisa)
@furter

to this team:
@libregraphicsmeeting/lgm-2016-website 

and provide that team access to the 2016 repo.

Thanks!!

If you want to contribute and aren't on the list, you may let us know in the comments below :)

**Comment by aoloe** [comment]
they're in and (i guess) got a notification of it being done

**Comment by barbarogenius** [comment]
thank you aoloe

**Comment by ms-studio** [comment]
We need to add Alice:

> I just signed up on github, my account name is @Alicepugini.

**Comment by aoloe** [comment]
she is in!

**Comment by ashsmith27** [comment]
Hi its Ashley (also a student), please would you be able to add me to the repository my username is @ashsmith27

**Comment by ms-studio** [comment]
Closing this issue for now.
