### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by ms-studio** [libregraphicsmeeting/htdocs-2016#3]
One thing we need to decide about is the folder structure.

I assume that this repository will contain: 

- the graphic files produced by alice, ashley, john
- a WordPress theme
- possibly some custom plugins written for the site

Those things could be kept in their own repos, but since they interact together it makes sense to keep all inside the repo.

So the structure could be something like:

- themes/lgm2016...
- plugins/custom-lgm2016-functions...
- design/

What do you think... makes sense? 

And what's the most appropriate name for the "design" folder? "iceberg"?

**Comment by barbarogenius** [comment]
hiya,

i think you mentioned "assets" as a word describing visual content. perhaps the general design is main folder and assets/images/etc are sub-folders? is iceberg referring to lettuce? or something else :)

**Comment by ms-studio** [comment]
"Iceberg" is referring to OSP's git folder structure, used by their Visual Culture git visualization tool :) 

http://osp.kitchen/tools/visualculture/

"asset" would be ok as well, but is often used for files actually used by the website, so it could lead to confusion...

**Comment by ms-studio** [comment]
Decision taken during worksession with a.l.e. : we name it "design".
