### ISSUE TITLE
Talk submission and rating process

### ISSUE THREAD

**Issue by ms-studio** [libregraphicsmeeting/htdocs-2016#5]
The talk submission / rating  is a workflow that includes several steps:

- submission of talk proposals through an online form.
- review / rating / validation of the talks by a jury.
- emailing feedback to the speakers.
- turning the accepted talks into the schedule of the LGM.
- allowing speakers to add information and slides to their talk. 

I think we have the tools and experience to improve that process and make it work without hassles. We should document how exactly we want those steps to work. 

Should be discussed with the Content Team.

**Comment by ms-studio** [comment]
To facilitate the rating of talks, we could use a plugin such as this:

https://wordpress.org/plugins/wp-postratings/screenshots/

**Comment by aoloe** [comment]
thanks for the proposal!

not sure wp-postratings does what we most have needed in the past years :-)

in the past, the reviewing tasks was mostly about:

- making sure that the submissions are on topic and remove the ones that are clearly bogus
- all others talks being by default accepted, there might be a discussion on individual submissions about the format and the length.
- eventually we get in touch with the speaker and try to get her to revise the submission.
- attributing tags to each submission could be helpful in sorting them when putting together the schedule.

the list in the ticket main description seems very good to me, but i'm not sure that rating is so important of us... of course, it can help to see how other people judge each talk. but it's not the core of our work.

our need seems rather go towards:

- seeing what other peole are saying about a talk,
- eventually reply to it and
- make sure that if there is a need to get in touch with the speaker, somebody will do it.

until now, we did it with a google spreadsheet but it was a pain to move back the changes that were made into wp.
so doing it through wp would be welcome to me (except if somebody has an issue with logging into wp, a think that we cannot exclude).

of course, this is only valid if we keep the same approach as the past years!

**Comment by ms-studio** [comment]
Ok, indeed the rating probably doesn't help much in that case.

What I propose in WP: some method that allows to set the **status** for each proposal. Could be handled by a custom taxonomy, or additions to the publication status of WordPress.

What would be the most useful "status" definitions for a talk?

- Pending
- Bogus/spam
- Needs discussion
- Needs speaker feedback
- Accepted
- Not accepted
- others?

- **Allow comments** : we could use the default WordPress comments, and simply avoid displaying them on the public side for the "Talks" content type.

Or we could make use of the [EditFlow plugin](https://github.com/automattic/edit-flow). It offers:

- [Custom statuses](http://editflow.org/features/custom-statuses/)
- [Editorial Comments](http://editflow.org/features/editorial-comments/)

**Comment by ms-studio** [comment]
Following last Saturday's discussion, we have a plan, lined out in issue #8. Closing this.
